FROM python:3.11-slim


WORKDIR /app


COPY sales-system/ui/requirements.txt .


RUN pip install --no-cache-dir -r requirements.txt


COPY sales-system/ui .


EXPOSE 8501


CMD ["streamlit", "run", "Home.py", "--server.port=8501", "--server.address=0.0.0.0"]
